module.exports = {
  content: ['index.html'],
  css: ['tailwind.min.css'],
  safelist: [
    'bg-gray-900',
    'flex',
    'justify-center',
    'items-center',
    'w-full',
    'h-full',
    'flex-col',
    'p-4',
    'lg:w-4/5',
    'lg:flex-row',
    'py-8',
    'border',
    'rounded',
    'border-gray-700',
    'bg-gray-800',
    'p-8',
    'lg:w-2/6',
    'lg:mt-0',
    'lg:ml-4',
    'w-full',
    'lg:w-4/6',
    'mt-4',
    'text-2xl',
    'lg:text-3xl',
    'font-semibold',
    'text-gray-200',
    'text-lg',
    'lg:text-xl',
    'font-thin',
    'text-gray-400',
    'text-center',
    'gap-4',
    'leading-7',
    'mt-16',
    'flex-wrap',
    'gap-2',
    'techs',
    'text-xl',
    'rounded-full',
    'w-24',
    'lg:w-72'
  ]
}